#!/bin/sh

#  curl https://raw.githubusercontent.com/ryanpcmcquen/linuxTweaks/master/slackware/sbopkg-recipes/inkscape | sh

sbopkg -i libsigc++ -i glibmm -i cairomm -i pangomm -i atkmm -i mm-common -i gtkmm -i gsl -i numpy -i BeautifulSoup -i lxml -i inkscape
