#!/bin/sh

GITNAME="Ryan P. C. McQuen"
GITEMAIL="ryanpcmcquen@member.fsf.org"
## git config
git config --global user.name "$GITNAME"
git config --global user.email "$GITEMAIL"
git config --global credential.helper 'cache --timeout=3600'
git config --global push.default simple
git config --global core.pager "less -r"

