#!/bin/sh
## i put it in /usr/local/etc/

sleep 2 &
if [ -e /usr/bin/trayer ]; then
  trayer --expand true --widthtype request --transparent true --edge top --align right --height 17 --margin 70 &
fi
if [ -x /etc/rc.d/rc.networkmanager ]; then
  nm-applet &
fi
if [ -x /etc/rc.d/rc.wicd ]; then
  wicd-client -t &
fi
if [ -e /usr/bin/CopyAgent ]; then
  CopyAgent &
fi

