#!/bin/sh
## put md5sums into the info file
## for easy updating

## standard tarballs
for ITEM in *.tar*; do
  md5sum $ITEM >> $(find *.info)
done
## ziperoonis
for ITEM in *.zip*; do
  md5sum $ITEM >> $(find *.info)
done
## those other tarballs
for ITEM in *.t?z*; do
  md5sum $ITEM >> $(find *.info)
done
## xzipped, gzipped, et cetera
for ITEM in *.?z*; do
  md5sum $ITEM >> $(find *.info)
done


