#!/bin/sh
## use SBo master git branch instead of a specific version
#wget -N https://raw.githubusercontent.com/ryanpcmcquen/linuxTweaks/master/slackware/sbo/90-SBo-master.repo \
#  -P /etc/sbopkg/repos.d/

## create sbopkg directories
mkdir -pv /var/lib/sbopkg/SBo-master/
mkdir -pv /var/lib/sbopkg/queues/
mkdir -pv /var/log/sbopkg/
mkdir -pv /var/cache/sbopkg/
mkdir -pv /tmp/SBo/
## reverse
#rm -rfv /var/lib/sbopkg/
#rm -rfv /var/log/sbopkg/
#rm -rfv /var/cache/sbopkg/
#rm -rfv /tmp/SBo/

