#!/bin/sh

## to replace this file as lilo simply run:
##
## cp /sbin/lilo /sbin/lilo.orig
## wget -N https://raw.githubusercontent.com/ryanpcmcquen/linuxTweaks/master/slackware/EFI/lilo -P /sbin/

ls --color=never /boot/vmlinuz* | tail -1 | xargs -i cp {} /boot/efi/EFI/boot/vmlinuz

