#!/bin/sh
no_prompt_sbo_pkg_install_upgrade() {
  SBO_PACKAGE=$1
  if [ ! -e /var/log/packages/$SBO_PACKAGE-* ] || [ ! -z $(sbopkg -c | grep $SBO_PACKAGE) ]; then
    echo p | sbopkg -B -e continue -i $SBO_PACKAGE
  fi
}

sed -i 's/^BATCH=off/BATCH=on/g' /etc/slackpkg/slackpkg.conf
sed -i 's/^DEFAULT_ANSWER=n/DEFAULT_ANSWER=y/g' /etc/slackpkg/slackpkg.conf

slackpkg update gpg
slackpkg update
slackpkg upgrade-all

sed -i 's/^BATCH=on/BATCH=off/g' /etc/slackpkg/slackpkg.conf
sed -i 's/^DEFAULT_ANSWER=y/DEFAULT_ANSWER=n/g' /etc/slackpkg/slackpkg.conf

no_prompt_sbo_pkg_install_upgrade jpegoptim
no_prompt_sbo_pkg_install_upgrade mozjpeg
no_prompt_sbo_pkg_install_upgrade optipng
no_prompt_sbo_pkg_install_upgrade pngquant
no_prompt_sbo_pkg_install_upgrade gifsicle
no_prompt_sbo_pkg_install_upgrade exiftool

wget -N https://raw.githubusercontent.com/ryanpcmcquen/image-ultimator/master/imgult; sudo install -m755 imgult /usr/local/bin/; rm imgult

ln -sfv /usr/local/bin/imgult /var/www/htdocs/imgult-web/
chown apache /usr/local/bin/imgult

